### ISSUE TITLE
Reusable grouping

### ISSUE THREAD

**Issue by bclaise** [netmod-wg/rfc6087bis#21]
During the YANG doctors lunch, we discussed: what does it mean to create a reusable grouping?
Do we want to say a few words about it? Any design guidelines.

**Comment by abierman** [comment]
Added this section:

*\* Reusable Groupings

A reusable grouping is a YANG grouping that can be imported
by another module, and is intended for use by other modules.
This is not the same as a grouping that is used within the
module it is defined, but happens to be exportable to another
module because it is defined at the top-level of the YANG module.

The following guidelines apply to reusable groupings,
in order to make them as robust as possible:
- Clearly identify the purpose of the grouping in the
  "description" statement.
- There are 5 different XPath contexts in YANG (rpc/input,
  rpc/output, notification, config=true data nodes, and all data nodes).
  Clearly identify which XPath contexts are applicable or excluded
  for the grouping.
- Do not reference data outside the grouping in any "path",
  "must", or "when" statements.
- Do not include a "default" sub-statement on a leaf or choice unless
  the value applies on all possible contexts.
- Do not include a "config" sub-statement on a data node unless
  the value applies on all possible contexts.
- Clearly identify any external dependencies in the grouping
  "description" statement, such as nodes referenced
  by absolute path from a "path", "must", or "when" statement.

**Comment by abierman** [comment]
closed in draft-05
